# Generated by Django 3.2.4 on 2022-06-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='isNumeric',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='range',
            field=models.IntegerField(default=1),
        ),
    ]
